/**
 * Synthetic studio data.
 *
 * Deliberately invented rather than lifted from `data/` — the prototype has to
 * show every failure mode (fabricated verse, duplicate, first-option bias,
 * blown budget, cancelled job) and real content does not contain them on demand.
 * Nothing here is imported by the live app.
 */

import type {
  AuditEntry,
  Draft,
  Job,
  Permission,
  Prompt,
  Provider,
  QualityMetric,
  Release,
  Role,
  ScriptureCheck,
  TopicNode,
} from './types';

/* ------------------------------------------------------------------- roles */

export const ROLE_LABEL: Record<Role, string> = {
  author: 'Автор',
  reviewer: 'Рецензент',
  admin: 'Адміністратор',
};

/**
 * `repair`, `approve` and `publish` are different permissioned operations —
 * the studio never collapses them into one "save" button.
 */
export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  author: ['job.run', 'job.cancel', 'draft.edit', 'draft.repair', 'review.comment'],
  reviewer: ['job.run', 'draft.repair', 'review.comment', 'review.approve'],
  admin: [
    'job.run',
    'job.cancel',
    'draft.edit',
    'draft.repair',
    'review.comment',
    'review.approve',
    'content.publish',
    'content.rollback',
    'settings.write',
  ],
};

export function can(role: Role, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role].includes(permission);
}

export const CURRENT_USER = {
  name: 'Денис П.',
  initials: 'ДП',
  handle: '@denys',
};

/* -------------------------------------------------------------- scripture */

export const SCRIPTURE_CHECKS: ScriptureCheck[] = [
  {
    id: 'sc-1',
    reference: 'Ів 3:16',
    normalized: 'JHN.3.16',
    translation: 'Огієнко',
    quoted: 'Так бо Бог полюбив світ, що дав Сина Свого Однородженого',
    source: 'Так бо Бог полюбив світ, що дав Сина Свого Однородженого',
    verdict: 'match',
    note: 'Цитата збігається з джерелом посимвольно.',
    draftId: 'd-102',
    checkedAt: '2026-09-17 09:12',
  },
  {
    id: 'sc-2',
    reference: 'Мт 5:9',
    normalized: 'MAT.5.9',
    translation: 'Огієнко',
    quoted: 'Блаженні миротворці, бо вони синами Божими стануть',
    source: 'Блаженні миротворці, бо вони синами Божими назвуться',
    verdict: 'paraphrase',
    note: 'Переказ близький до тексту, але не дослівний. Потрібне рішення рецензента: лапки зняти або цитату виправити.',
    draftId: 'd-104',
    checkedAt: '2026-09-17 09:12',
  },
  {
    id: 'sc-3',
    reference: 'Прит 31:31',
    normalized: 'PRO.31.31',
    translation: 'Огієнко',
    quoted: 'Мудрість починається зі служіння ближньому',
    source: 'Дайте їй з плоду рук її, і нехай її вчинки її вихваляють',
    verdict: 'mismatch',
    note: 'Цитата не відповідає посиланню. Модель підставила чужий текст.',
    draftId: 'd-108',
    checkedAt: '2026-09-17 09:12',
  },
  {
    id: 'sc-4',
    reference: 'Ів 21:26',
    normalized: 'JHN.21.26',
    translation: 'Огієнко',
    quoted: 'І сказав Він учням: не бійтеся малого стада',
    source: null,
    verdict: 'not_found',
    note: 'Вірша не існує: у Івана 21 лише 25 віршів. Чернетку заблоковано автоматично.',
    draftId: 'd-109',
    checkedAt: '2026-09-17 09:13',
  },
  {
    id: 'sc-5',
    reference: '1 Кор 13:4-7',
    normalized: '1CO.13.4-7',
    translation: 'Огієнко',
    quoted: 'Любов довготерпить, любов милосердствує',
    source: 'Любов довготерпить, любов милосердствує',
    verdict: 'match',
    note: 'Діапазон віршів нормалізовано, перевірено перший вірш діапазону.',
    draftId: 'd-101',
    checkedAt: '2026-09-17 08:41',
  },
  {
    id: 'sc-6',
    reference: 'Дії 2:38',
    normalized: 'ACT.2.38',
    translation: 'Огієнко',
    quoted: 'Покайтеся, і нехай же охриститься кожен із вас',
    source: 'Покайтеся, і нехай же охриститься кожен із вас',
    verdict: 'match',
    note: 'Збіг. Evidence збережено разом із ревізією.',
    draftId: 'd-103',
    checkedAt: '2026-09-17 08:40',
  },
];

/* ----------------------------------------------------------------- drafts */

export const DRAFTS: Draft[] = [
  {
    id: 'd-101',
    kind: 'question',
    title: 'Ознаки любові за апостолом Павлом',
    topicId: 't-epistles-love',
    topicPath: 'Новий Заповіт · Послання · Любов',
    status: 'ready_for_review',
    revision: 3,
    author: 'job:gen-4821',
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    jobId: 'j-4821',
    createdAt: '2026-09-17 08:38',
    updatedAt: '2026-09-17 08:41',
    scriptureIds: ['sc-5'],
    checks: [
      { id: 'c1', label: 'Схема', severity: 'pass', detail: 'Усі обовʼязкові поля на місці, 4 варіанти.', kind: 'deterministic' },
      { id: 'c2', label: 'Правильна відповідь', severity: 'pass', detail: 'correctIndex = 2, підтверджено джерелом.', kind: 'deterministic' },
      { id: 'c3', label: 'Дублікати', severity: 'pass', detail: 'Найближчий збіг 0.41 (поріг 0.86).', kind: 'deterministic' },
      { id: 'c4', label: 'Мова', severity: 'pass', detail: 'Українська, без русизмів у словнику.', kind: 'deterministic' },
      { id: 'c5', label: 'Писання', severity: 'pass', detail: '1 Кор 13:4-7 — збіг із джерелом.', kind: 'deterministic' },
      { id: 'c6', label: 'Богословська чутливість', severity: 'warn', detail: 'Тема доктринальна — потрібне людське підтвердження формулювання.', kind: 'human' },
    ],
    diff: [
      { field: 'prompt', kind: 'changed', before: 'Що Павло каже про любов?', after: 'Яку рису любові апостол Павло називає першою в 1 Кор 13:4?' },
      { field: 'options[0]', kind: 'unchanged', before: 'Вона заздрить', after: 'Вона заздрить' },
      { field: 'options[1]', kind: 'changed', before: 'Вона пишається', after: 'Вона величається' },
      { field: 'options[2]', kind: 'changed', before: 'Вона терпить', after: 'Вона довготерпить' },
      { field: 'options[3]', kind: 'unchanged', before: 'Вона шукає свого', after: 'Вона шукає свого' },
      { field: 'explanation', kind: 'changed', before: 'Павло починає з терпіння.', after: 'Перелік у 1 Кор 13:4 починається саме з довготерпіння — це перша названа риса.' },
      { field: 'reference', kind: 'added', before: null, after: '1 Кор 13:4-7' },
    ],
    comments: [
      { id: 'cm1', author: 'Оксана Р.', role: 'reviewer', at: '2026-09-17 09:02', body: 'Варіант «Вона величається» звучить архаїчно, але це слово з перекладу Огієнка — лишаємо.' },
    ],
    question: {
      prompt: 'Яку рису любові апостол Павло називає першою в 1 Кор 13:4?',
      options: ['Вона заздрить', 'Вона величається', 'Вона довготерпить', 'Вона шукає свого'],
      correctIndex: 2,
      explanation: 'Перелік у 1 Кор 13:4 починається саме з довготерпіння — це перша названа риса.',
      reference: '1 Кор 13:4-7',
      difficulty: 'easy',
    },
  },
  {
    id: 'd-102',
    kind: 'question',
    title: 'Найвідоміший вірш Євангелія від Івана',
    topicId: 't-gospels-john',
    topicPath: 'Новий Заповіт · Євангелія · Іван',
    status: 'ready_for_review',
    revision: 1,
    author: 'job:gen-4821',
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    jobId: 'j-4821',
    createdAt: '2026-09-17 09:10',
    updatedAt: '2026-09-17 09:12',
    scriptureIds: ['sc-1'],
    checks: [
      { id: 'c1', label: 'Схема', severity: 'pass', detail: 'Валідна.', kind: 'deterministic' },
      { id: 'c2', label: 'Дублікати', severity: 'warn', detail: 'Схожість 0.88 із q-7741 «Кого Бог дав світові?» — вище порогу 0.86.', kind: 'deterministic' },
      { id: 'c3', label: 'Зміщення до першого варіанта', severity: 'warn', detail: 'У цьому джобі 7 із 12 правильних відповідей на позиції 0.', kind: 'deterministic' },
      { id: 'c4', label: 'Писання', severity: 'pass', detail: 'Ів 3:16 — збіг.', kind: 'deterministic' },
    ],
    diff: [
      { field: 'prompt', kind: 'added', before: null, after: 'Кого, за словами Івана 3:16, Бог дав світові?' },
      { field: 'options', kind: 'added', before: null, after: '4 варіанти' },
      { field: 'correctIndex', kind: 'added', before: null, after: '0' },
      { field: 'reference', kind: 'added', before: null, after: 'Ів 3:16' },
    ],
    comments: [],
    question: {
      prompt: 'Кого, за словами Івана 3:16, Бог дав світові?',
      options: ['Сина Свого Однородженого', 'Пророка Іллю', 'Закон Мойсеїв', 'Ангела Господнього'],
      correctIndex: 0,
      explanation: 'Ів 3:16 говорить про Сина Однородженого — центральний вірш Євангелія.',
      reference: 'Ів 3:16',
      difficulty: 'easy',
    },
  },
  {
    id: 'd-103',
    kind: 'explanation',
    title: 'Пояснення до питання про Пʼятидесятницю',
    topicId: 't-acts-pentecost',
    topicPath: 'Новий Заповіт · Дії · Пʼятидесятниця',
    status: 'changes_requested',
    revision: 2,
    author: 'job:exp-4790',
    provider: 'ollama',
    model: 'llama3.1:8b',
    jobId: 'j-4790',
    createdAt: '2026-09-16 21:04',
    updatedAt: '2026-09-17 08:40',
    scriptureIds: ['sc-6'],
    checks: [
      { id: 'c1', label: 'Схема', severity: 'pass', detail: 'Валідна.', kind: 'deterministic' },
      { id: 'c2', label: 'Довжина', severity: 'warn', detail: '412 символів при ліміті 280 — обріжеться на телефоні.', kind: 'deterministic' },
      { id: 'c3', label: 'Писання', severity: 'pass', detail: 'Дії 2:38 — збіг.', kind: 'deterministic' },
      { id: 'c4', label: 'Тон', severity: 'warn', detail: 'Формулювання ближче до проповіді, ніж до пояснення факту.', kind: 'ai' },
    ],
    diff: [
      { field: 'explanation', kind: 'changed', before: 'Петро закликав до покаяння і хрищення.', after: 'У день Пʼятидесятниці Петро звернувся до натовпу і закликав покаятися та охриститися в імʼя Ісуса Христа — саме з цієї проповіді починається історія церкви, і кожен, хто чує цей заклик сьогодні, стоїть перед тим самим вибором…' },
    ],
    comments: [
      { id: 'cm2', author: 'Оксана Р.', role: 'reviewer', at: '2026-09-17 08:40', body: 'Прибрати заклик до читача — пояснення має пояснювати відповідь, а не проповідувати. І вкластися у 280 символів.' },
    ],
  },
  {
    id: 'd-104',
    kind: 'question',
    title: 'Заповіді блаженства: миротворці',
    topicId: 't-gospels-sermon',
    topicPath: 'Новий Заповіт · Євангелія · Нагірна проповідь',
    status: 'ready_for_review',
    revision: 1,
    author: 'job:gen-4821',
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    jobId: 'j-4821',
    createdAt: '2026-09-17 09:11',
    updatedAt: '2026-09-17 09:12',
    scriptureIds: ['sc-2'],
    checks: [
      { id: 'c1', label: 'Схема', severity: 'pass', detail: 'Валідна.', kind: 'deterministic' },
      { id: 'c2', label: 'Писання', severity: 'warn', detail: 'Мт 5:9 — переказ, а не цитата. Потрібне рішення людини.', kind: 'deterministic' },
      { id: 'c3', label: 'Дублікати', severity: 'pass', detail: 'Найближчий збіг 0.52.', kind: 'deterministic' },
    ],
    diff: [
      { field: 'prompt', kind: 'added', before: null, after: 'Кого, за Нагірною проповіддю, названо синами Божими?' },
      { field: 'explanation', kind: 'added', before: null, after: 'Мт 5:9 — сьома заповідь блаженства.' },
    ],
    comments: [],
    question: {
      prompt: 'Кого, за Нагірною проповіддю, названо синами Божими?',
      options: ['Убогих духом', 'Миротворців', 'Голодних і спраглих правди', 'Чистих серцем'],
      correctIndex: 1,
      explanation: 'Мт 5:9 — сьома заповідь блаженства: «Блаженні миротворці, бо вони синами Божими назвуться».',
      reference: 'Мт 5:9',
      difficulty: 'medium',
    },
  },
  {
    id: 'd-108',
    kind: 'question',
    title: 'Доброчесна жінка в Приповістях',
    topicId: 't-wisdom-proverbs',
    topicPath: 'Старий Заповіт · Мудрість · Приповісті',
    status: 'validation_failed',
    revision: 1,
    author: 'job:gen-4822',
    provider: 'ollama',
    model: 'llama3.1:8b',
    jobId: 'j-4822',
    createdAt: '2026-09-17 09:31',
    updatedAt: '2026-09-17 09:31',
    scriptureIds: ['sc-3'],
    checks: [
      { id: 'c1', label: 'Схема', severity: 'pass', detail: 'Валідна.', kind: 'deterministic' },
      { id: 'c2', label: 'Писання', severity: 'fail', detail: 'Прит 31:31 — цитата не відповідає посиланню.', kind: 'deterministic' },
      { id: 'c3', label: 'Правильна відповідь', severity: 'fail', detail: 'Жоден варіант не підтверджується джерелом.', kind: 'deterministic' },
    ],
    diff: [
      { field: 'prompt', kind: 'added', before: null, after: 'З чого, за Приповістями 31, починається мудрість?' },
      { field: 'reference', kind: 'added', before: null, after: 'Прит 31:31' },
    ],
    comments: [],
    question: {
      prompt: 'З чого, за Приповістями 31, починається мудрість?',
      options: ['Зі служіння ближньому', 'Зі страху Господнього', 'З мовчання', 'З посту'],
      correctIndex: 0,
      explanation: 'Мудрість починається зі служіння ближньому.',
      reference: 'Прит 31:31',
      difficulty: 'medium',
    },
  },
  {
    id: 'd-109',
    kind: 'question',
    title: 'Слова Ісуса учням після воскресіння',
    topicId: 't-gospels-john',
    topicPath: 'Новий Заповіт · Євангелія · Іван',
    status: 'validation_failed',
    revision: 1,
    author: 'job:gen-4822',
    provider: 'ollama',
    model: 'llama3.1:8b',
    jobId: 'j-4822',
    createdAt: '2026-09-17 09:32',
    updatedAt: '2026-09-17 09:32',
    scriptureIds: ['sc-4'],
    checks: [
      { id: 'c1', label: 'Схема', severity: 'pass', detail: 'Валідна.', kind: 'deterministic' },
      { id: 'c2', label: 'Писання', severity: 'fail', detail: 'Ів 21:26 не існує — у розділі 25 віршів.', kind: 'deterministic' },
    ],
    diff: [
      { field: 'reference', kind: 'added', before: null, after: 'Ів 21:26' },
    ],
    comments: [],
    question: {
      prompt: 'Що, за Іваном 21:26, Ісус сказав учням?',
      options: ['Не бійтеся малого стада', 'Мир вам', 'Ідіть і навчайте', 'Пасіть овець Моїх'],
      correctIndex: 0,
      explanation: 'І сказав Він учням: не бійтеся малого стада.',
      reference: 'Ів 21:26',
      difficulty: 'hard',
    },
  },
  {
    id: 'd-110',
    kind: 'question',
    title: 'Перший цар Ізраїлю',
    topicId: 't-history-kings',
    topicPath: 'Старий Заповіт · Історія · Царі',
    status: 'approved',
    revision: 4,
    author: 'Оксана Р.',
    provider: 'mock',
    model: 'mock-1',
    jobId: null,
    createdAt: '2026-09-16 14:02',
    updatedAt: '2026-09-17 07:55',
    scriptureIds: [],
    checks: [
      { id: 'c1', label: 'Схема', severity: 'pass', detail: 'Валідна.', kind: 'deterministic' },
      { id: 'c2', label: 'Дублікати', severity: 'pass', detail: 'Найближчий збіг 0.33.', kind: 'deterministic' },
      { id: 'c3', label: 'Людське ревʼю', severity: 'pass', detail: 'Схвалено Оксаною Р. 17.09 о 07:55.', kind: 'human' },
    ],
    diff: [
      { field: 'options[3]', kind: 'changed', before: 'Соломон', after: 'Ровоам' },
    ],
    comments: [
      { id: 'cm3', author: 'Оксана Р.', role: 'reviewer', at: '2026-09-17 07:55', body: 'Замінила Соломона на Ровоама — інакше три з чотирьох варіантів надто очевидні.', resolved: true },
    ],
    question: {
      prompt: 'Хто був першим царем обʼєднаного Ізраїлю?',
      options: ['Саул', 'Давид', 'Самуїл', 'Ровоам'],
      correctIndex: 0,
      explanation: 'Саула помазав Самуїл — це початок царського періоду.',
      reference: '1 Сам 10:1',
      difficulty: 'easy',
    },
  },
  {
    id: 'd-111',
    kind: 'topic',
    title: 'Нова підтема: «Притчі про Царство»',
    topicId: 't-gospels-parables',
    topicPath: 'Новий Заповіт · Євангелія · Притчі',
    status: 'generated',
    revision: 1,
    author: 'job:top-4815',
    provider: 'omniroute',
    model: 'claude-sonnet-4',
    jobId: 'j-4815',
    createdAt: '2026-09-17 06:20',
    updatedAt: '2026-09-17 06:24',
    scriptureIds: [],
    checks: [
      { id: 'c1', label: 'Схема', severity: 'pass', detail: 'Валідна.', kind: 'deterministic' },
      { id: 'c2', label: 'Сироти', severity: 'warn', detail: 'Підтема створена без жодного питання в пулі.', kind: 'deterministic' },
    ],
    diff: [
      { field: 'title', kind: 'added', before: null, after: 'Притчі про Царство' },
      { field: 'parent', kind: 'added', before: null, after: 'Новий Заповіт · Євангелія' },
      { field: 'references', kind: 'added', before: null, after: 'Мт 13, Мк 4, Лк 13' },
    ],
    comments: [],
  },
];

/* ------------------------------------------------------------------- jobs */

export const JOBS: Job[] = [
  {
    id: 'j-4823',
    task: 'questions:generate',
    taskLabel: 'Генерація питань',
    requester: CURRENT_USER.name,
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    status: 'running',
    inputHash: 'sha256:9f2c…a41b',
    attempts: 1,
    maxAttempts: 3,
    startedAt: '2026-09-17 09:44',
    finishedAt: null,
    itemsDone: 14,
    itemsTotal: 40,
    step: 'Генерація партії 2 з 4',
    budget: { requests: 18, requestLimit: 60, tokens: 42_100, tokenLimit: 200_000, costUsd: 0.14, costLimitUsd: 1.5 },
    checkpoint: 'batch-2/item-14',
    retention: 'raw-артефакти 14 днів',
    target: 'Старий Заповіт · Пророки · Ісая',
    resultRef: null,
    logs: [
      { at: '09:44:02', level: 'info', text: 'job accepted · task=questions:generate · provider=gemini model=gemini-2.5-flash' },
      { at: '09:44:02', level: 'info', text: 'input hash sha256:9f2c…a41b · budget 60 req / 200k tok / $1.50' },
      { at: '09:44:09', level: 'info', text: 'batch 1/4 → 10 items generated in 6.8s' },
      { at: '09:44:11', level: 'warn', text: 'item 7: correctIndex відсутній → повторний запит (без fallback)' },
      { at: '09:44:18', level: 'info', text: 'batch 1/4 → schema ok 10/10 · duplicates 1 warn' },
      { at: '09:44:31', level: 'info', text: 'checkpoint saved: batch-2/item-14' },
    ],
  },
  {
    id: 'j-4822',
    task: 'questions:generate',
    taskLabel: 'Генерація питань',
    requester: CURRENT_USER.name,
    provider: 'ollama',
    model: 'llama3.1:8b',
    status: 'partial',
    inputHash: 'sha256:4be1…77d0',
    attempts: 2,
    maxAttempts: 3,
    startedAt: '2026-09-17 09:26',
    finishedAt: '2026-09-17 09:33',
    itemsDone: 12,
    itemsTotal: 20,
    step: 'Завершено з відхиленнями',
    budget: { requests: 34, requestLimit: 40, tokens: 88_400, tokenLimit: 120_000, costUsd: 0, costLimitUsd: 0 },
    checkpoint: null,
    retention: 'raw-артефакти 14 днів',
    target: 'Старий Заповіт · Мудрість · Приповісті',
    resultRef: '12 чернеток · 8 відхилено валідацією',
    logs: [
      { at: '09:26:40', level: 'info', text: 'job accepted · local provider · cost tracking disabled' },
      { at: '09:29:12', level: 'error', text: 'item 9: Scripture mismatch (Прит 31:31) → validation_failed' },
      { at: '09:31:55', level: 'error', text: 'item 14: reference not found (Ів 21:26) → validation_failed' },
      { at: '09:33:01', level: 'warn', text: 'завершено частково: 12 ok, 8 fail. Нічого не записано в published store.' },
    ],
  },
  {
    id: 'j-4821',
    task: 'questions:generate',
    taskLabel: 'Генерація питань',
    requester: 'Оксана Р.',
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    status: 'completed',
    inputHash: 'sha256:1a77…c302',
    attempts: 1,
    maxAttempts: 3,
    startedAt: '2026-09-17 08:34',
    finishedAt: '2026-09-17 08:42',
    itemsDone: 12,
    itemsTotal: 12,
    step: 'Завершено',
    budget: { requests: 16, requestLimit: 40, tokens: 37_900, tokenLimit: 120_000, costUsd: 0.11, costLimitUsd: 1 },
    checkpoint: null,
    retention: 'raw-артефакти 14 днів',
    target: 'Новий Заповіт · Євангелія + Послання',
    resultRef: '12 чернеток у черзі ревʼю',
    logs: [
      { at: '08:34:10', level: 'info', text: 'job accepted · 12 items requested' },
      { at: '08:41:02', level: 'warn', text: 'first-option bias: 7/12 correctIndex = 0 → позначено для ревʼю' },
      { at: '08:42:00', level: 'info', text: 'done: 12 drafts → ready_for_review' },
    ],
  },
  {
    id: 'j-4820',
    task: 'scripture:verify',
    taskLabel: 'Перевірка Писання',
    requester: 'system',
    provider: 'mock',
    model: 'reference-adapter',
    status: 'completed',
    inputHash: 'sha256:cc90…12fa',
    attempts: 1,
    maxAttempts: 2,
    startedAt: '2026-09-17 08:30',
    finishedAt: '2026-09-17 08:31',
    itemsDone: 148,
    itemsTotal: 148,
    step: 'Завершено',
    budget: { requests: 148, requestLimit: 500, tokens: 0, tokenLimit: 0, costUsd: 0, costLimitUsd: 0 },
    checkpoint: null,
    retention: 'evidence зберігається разом із ревізією',
    target: 'Усі чернетки в черзі',
    resultRef: '142 збіги · 4 перекази · 2 помилки',
    logs: [
      { at: '08:30:02', level: 'info', text: 'reference adapter: Огієнко (локальний індекс)' },
      { at: '08:31:40', level: 'info', text: 'done: 148 посилань перевірено, evidence збережено' },
    ],
  },
  {
    id: 'j-4819',
    task: 'explanations:repair',
    taskLabel: 'Ремонт пояснень',
    requester: CURRENT_USER.name,
    provider: 'omniroute',
    model: 'claude-sonnet-4',
    status: 'failed',
    inputHash: 'sha256:7e00…9b31',
    attempts: 3,
    maxAttempts: 3,
    startedAt: '2026-09-17 07:15',
    finishedAt: '2026-09-17 07:22',
    itemsDone: 3,
    itemsTotal: 30,
    step: 'Вичерпано спроби',
    budget: { requests: 40, requestLimit: 40, tokens: 119_000, tokenLimit: 120_000, costUsd: 0.98, costLimitUsd: 1 },
    checkpoint: 'item-3',
    retention: 'raw-артефакти 14 днів',
    target: 'Пояснення з позначкою «занадто довге»',
    resultRef: null,
    logs: [
      { at: '07:15:00', level: 'info', text: 'job accepted · 30 items' },
      { at: '07:18:31', level: 'error', text: 'provider 429 · retry 1/3 через 20s' },
      { at: '07:20:44', level: 'error', text: 'provider 429 · retry 2/3 через 40s' },
      { at: '07:22:02', level: 'error', text: 'бюджет запитів вичерпано (40/40) → job зупинено, checkpoint item-3 збережено' },
    ],
  },
  {
    id: 'j-4815',
    task: 'topics:expand',
    taskLabel: 'Конвеєр тем',
    requester: 'Оксана Р.',
    provider: 'omniroute',
    model: 'claude-sonnet-4',
    status: 'completed',
    inputHash: 'sha256:2d41…0ee7',
    attempts: 1,
    maxAttempts: 2,
    startedAt: '2026-09-17 06:18',
    finishedAt: '2026-09-17 06:24',
    itemsDone: 6,
    itemsTotal: 6,
    step: 'Завершено',
    budget: { requests: 9, requestLimit: 30, tokens: 22_500, tokenLimit: 80_000, costUsd: 0.22, costLimitUsd: 1 },
    checkpoint: null,
    retention: 'raw-артефакти 14 днів',
    target: 'Новий Заповіт · Євангелія',
    resultRef: '6 підтем · 1 без пулу питань',
    logs: [
      { at: '06:18:00', level: 'info', text: 'job accepted · 6 підтем' },
      { at: '06:24:00', level: 'info', text: 'done · 1 підтема без питань → позначено як сирота' },
    ],
  },
  {
    id: 'j-4812',
    task: 'questions:dedupe',
    taskLabel: 'Пошук дублікатів',
    requester: CURRENT_USER.name,
    provider: 'mock',
    model: 'embeddings-local',
    status: 'cancelled',
    inputHash: 'sha256:88aa…4401',
    attempts: 1,
    maxAttempts: 1,
    startedAt: '2026-09-16 22:10',
    finishedAt: '2026-09-16 22:12',
    itemsDone: 320,
    itemsTotal: 4100,
    step: 'Скасовано користувачем',
    budget: { requests: 8, requestLimit: 100, tokens: 0, tokenLimit: 0, costUsd: 0, costLimitUsd: 0 },
    checkpoint: 'offset-320',
    retention: '—',
    target: 'Увесь банк питань',
    resultRef: null,
    logs: [
      { at: '22:10:00', level: 'info', text: 'job accepted · 4100 items' },
      { at: '22:12:18', level: 'warn', text: 'cancel requested by Денис П. · checkpoint offset-320 збережено, можна продовжити' },
    ],
  },
  {
    id: 'j-4824',
    task: 'questions:generate',
    taskLabel: 'Генерація питань',
    requester: CURRENT_USER.name,
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    status: 'queued',
    inputHash: 'sha256:5c10…bb92',
    attempts: 0,
    maxAttempts: 3,
    startedAt: '—',
    finishedAt: null,
    itemsDone: 0,
    itemsTotal: 25,
    step: 'У черзі за j-4823',
    budget: { requests: 0, requestLimit: 60, tokens: 0, tokenLimit: 200_000, costUsd: 0, costLimitUsd: 1.5 },
    checkpoint: null,
    retention: 'raw-артефакти 14 днів',
    target: 'Новий Заповіт · Дії',
    resultRef: null,
    logs: [{ at: '09:45:10', level: 'info', text: 'job queued · стартує після j-4823' }],
  },
];

/* ----------------------------------------------------------------- topics */

export const TOPIC_TREE: TopicNode[] = [
  {
    id: 't-ot',
    title: 'Старий Заповіт',
    reference: 'Буття — Малахія',
    updatedAt: '2026-09-17',
    flags: [],
    accuracy: 0.71,
    pool: { published: 1840, inReview: 21, target: 2000 },
    children: [
      {
        id: 't-history-kings',
        title: 'Історія · Царі',
        reference: '1 Сам — 2 Хр',
        updatedAt: '2026-09-17',
        flags: [],
        accuracy: 0.74,
        pool: { published: 310, inReview: 1, target: 320 },
      },
      {
        id: 't-wisdom-proverbs',
        title: 'Мудрість · Приповісті',
        reference: 'Прит 1—31',
        updatedAt: '2026-09-17',
        flags: ['2 відхилені чернетки', 'низька складність'],
        accuracy: 0.86,
        pool: { published: 96, inReview: 2, target: 180 },
      },
      {
        id: 't-prophets-isaiah',
        title: 'Пророки · Ісая',
        reference: 'Іс 1—66',
        updatedAt: '2026-09-17',
        flags: ['генерація триває'],
        accuracy: 0.58,
        pool: { published: 42, inReview: 14, target: 160 },
      },
    ],
  },
  {
    id: 't-nt',
    title: 'Новий Заповіт',
    reference: 'Матвій — Об’явлення',
    updatedAt: '2026-09-17',
    flags: [],
    accuracy: 0.79,
    pool: { published: 2260, inReview: 18, target: 2400 },
    children: [
      {
        id: 't-gospels-john',
        title: 'Євангелія · Іван',
        reference: 'Ів 1—21',
        updatedAt: '2026-09-17',
        flags: ['1 дублікат'],
        accuracy: 0.81,
        pool: { published: 288, inReview: 2, target: 300 },
      },
      {
        id: 't-gospels-sermon',
        title: 'Євангелія · Нагірна проповідь',
        reference: 'Мт 5—7',
        updatedAt: '2026-09-17',
        flags: [],
        accuracy: 0.77,
        pool: { published: 140, inReview: 1, target: 150 },
      },
      {
        id: 't-gospels-parables',
        title: 'Євангелія · Притчі про Царство',
        reference: 'Мт 13, Мк 4, Лк 13',
        updatedAt: '2026-09-17',
        flags: ['сирота: пул порожній'],
        accuracy: null,
        pool: { published: 0, inReview: 0, target: 120 },
      },
      {
        id: 't-acts-pentecost',
        title: 'Дії · Пʼятидесятниця',
        reference: 'Дії 1—2',
        updatedAt: '2026-09-17',
        flags: ['пояснення на доопрацюванні'],
        accuracy: 0.69,
        pool: { published: 74, inReview: 1, target: 120 },
      },
      {
        id: 't-epistles-love',
        title: 'Послання · Любов',
        reference: '1 Кор 13',
        updatedAt: '2026-09-17',
        flags: [],
        accuracy: 0.9,
        pool: { published: 58, inReview: 1, target: 80 },
      },
    ],
  },
];

/* --------------------------------------------------------------- releases */

export const RELEASES: Release[] = [
  {
    id: 'r-58',
    version: 'content 2026.09.5',
    publishedAt: '2026-09-16 18:40',
    publishedBy: 'Денис П.',
    items: 96,
    topics: ['Євангелія · Іван', 'Послання · Любов'],
    status: 'published',
    note: 'Плановий випуск. Усі 96 позицій мають evidence Писання.',
    canRollback: true,
  },
  {
    id: 'r-57',
    version: 'content 2026.09.4',
    publishedAt: '2026-09-14 12:05',
    publishedBy: 'Денис П.',
    items: 41,
    topics: ['Історія · Царі'],
    status: 'published',
    note: 'Виправлення формулювань після скарг гравців.',
    canRollback: true,
  },
  {
    id: 'r-56',
    version: 'content 2026.09.3',
    publishedAt: '2026-09-12 09:15',
    publishedBy: 'Оксана Р.',
    items: 18,
    topics: ['Мудрість · Приповісті'],
    status: 'rolled_back',
    note: 'Відкочено 12.09 о 11:02 — у 5 питаннях правильна відповідь не збігалася з поясненням.',
    canRollback: false,
  },
  {
    id: 'r-59',
    version: 'content 2026.09.6',
    publishedAt: '2026-09-18 08:00',
    publishedBy: 'Денис П.',
    items: 12,
    topics: ['Пророки · Ісая'],
    status: 'scheduled',
    note: 'Заплановано. Публікація стартує тільки якщо всі 12 позицій approved.',
    canRollback: false,
  },
];

/* ------------------------------------------------------------------ audit */

export const AUDIT: AuditEntry[] = [
  { id: 'a-1', at: '2026-09-17 09:45', actor: 'Денис П.', role: 'admin', action: 'job.run', target: 'j-4824', detail: 'questions:generate · Дії · 25 позицій · бюджет $1.50', evidence: 'input sha256:5c10…bb92' },
  { id: 'a-2', at: '2026-09-17 09:33', actor: 'system', role: 'admin', action: 'draft.reject', target: 'd-108, d-109', detail: 'Scripture mismatch / reference not found', evidence: 'sc-3, sc-4' },
  { id: 'a-3', at: '2026-09-17 08:40', actor: 'Оксана Р.', role: 'reviewer', action: 'review.changes_requested', target: 'd-103', detail: 'Тон і довжина пояснення', evidence: 'коментар cm2' },
  { id: 'a-4', at: '2026-09-17 07:55', actor: 'Оксана Р.', role: 'reviewer', action: 'review.approve', target: 'd-110', detail: 'ревізія 4 схвалена', evidence: 'diff options[3]' },
  { id: 'a-5', at: '2026-09-17 07:22', actor: 'system', role: 'admin', action: 'job.budget_exceeded', target: 'j-4819', detail: 'requests 40/40 → зупинено', evidence: 'логи j-4819' },
  { id: 'a-6', at: '2026-09-16 18:40', actor: 'Денис П.', role: 'admin', action: 'content.publish', target: 'r-58', detail: '96 позицій · 2 теми', evidence: 'реліз r-58' },
  { id: 'a-7', at: '2026-09-16 22:12', actor: 'Денис П.', role: 'admin', action: 'job.cancel', target: 'j-4812', detail: 'checkpoint offset-320 збережено', evidence: 'логи j-4812' },
  { id: 'a-8', at: '2026-09-12 11:02', actor: 'Денис П.', role: 'admin', action: 'content.rollback', target: 'r-56', detail: '18 позицій повернуто до попередньої ревізії', evidence: 'реліз r-56' },
  { id: 'a-9', at: '2026-09-12 10:40', actor: 'Олег К.', role: 'author', action: 'settings.write', target: 'provider:gemini', detail: 'модель gemini-2.0-flash → gemini-2.5-flash', evidence: 'відхилено: бракує прав' },
];

/* -------------------------------------------------------------- providers */

export const PROVIDERS: Provider[] = [
  {
    id: 'gemini',
    label: 'Gemini',
    status: 'connected',
    models: ['gemini-3.1-flash-lite', 'gemini-2.5-flash', 'gemini-2.0-flash', 'gemini-1.5-pro'],
    defaultModel: 'gemini-2.5-flash',
    envKeys: ['GEMINI_API_KEY', 'GEMINI_MODEL'],
    monthly: { tokens: 1_240_000, tokenLimit: 5_000_000, costUsd: 4.12, costLimitUsd: 25 },
    latencyMs: 640,
    note: 'Основний провайдер для генерації питань.',
  },
  {
    id: 'ollama',
    label: 'Ollama',
    status: 'degraded',
    models: ['llama3.1:8b', 'mistral:7b', 'gemma2:9b'],
    defaultModel: 'llama3.1:8b',
    envKeys: ['OLLAMA_HOST', 'OLLAMA_MODEL'],
    monthly: { tokens: 3_900_000, tokenLimit: 0, costUsd: 0, costLimitUsd: 0 },
    latencyMs: 2870,
    note: 'Локальний. Затримка вища за норму — модель вивантажується з памʼяті між джобами.',
  },
  {
    id: 'omniroute',
    label: 'OmniRoute',
    status: 'connected',
    models: ['claude-sonnet-4', 'gpt-4.1-mini'],
    defaultModel: 'claude-sonnet-4',
    envKeys: ['OMNIROUTE_API_KEY', 'OMNIROUTE_MODEL'],
    monthly: { tokens: 410_000, tokenLimit: 2_000_000, costUsd: 6.4, costLimitUsd: 20 },
    latencyMs: 1120,
    note: 'Для складних завдань: теми, ремонт пояснень.',
  },
  {
    id: 'mock',
    label: 'MockProvider',
    status: 'connected',
    models: ['mock-1', 'embeddings-local', 'reference-adapter'],
    defaultModel: 'mock-1',
    envKeys: [],
    monthly: { tokens: 0, tokenLimit: 0, costUsd: 0, costLimitUsd: 0 },
    latencyMs: 12,
    note: 'Детермінований. Покриває orchestration-тести — без нього CI не проходить.',
  },
];

export const PROMPTS: Prompt[] = [
  {
    id: 'p-1',
    name: 'questions.generate',
    version: 'v7',
    updatedAt: '2026-09-15',
    updatedBy: 'Денис П.',
    usedBy: ['questions:generate'],
    excerpt: 'Згенеруй питання з 4 варіантами українською. Точно один правильний. Обовʼязкове посилання на Писання у форматі «Книга розділ:вірш». Не вигадуй віршів…',
  },
  {
    id: 'p-2',
    name: 'explanations.repair',
    version: 'v3',
    updatedAt: '2026-09-11',
    updatedBy: 'Оксана Р.',
    usedBy: ['explanations:repair'],
    excerpt: 'Перепиши пояснення до 280 символів. Пояснюй, чому відповідь правильна, не звертайся до читача, не проповідуй…',
  },
  {
    id: 'p-3',
    name: 'topics.expand',
    version: 'v2',
    updatedAt: '2026-09-02',
    updatedBy: 'Денис П.',
    usedBy: ['topics:expand'],
    excerpt: 'Запропонуй підтеми для заданого розділу. Кожна підтема має щонайменше три посилання на Писання…',
  },
  {
    id: 'p-4',
    name: 'scripture.verify',
    version: 'v4',
    updatedAt: '2026-09-16',
    updatedBy: 'system',
    usedBy: ['scripture:verify'],
    excerpt: 'Детермінований адаптер. Промпт використовується лише для класифікації «переказ vs цитата»…',
  },
];

/* ---------------------------------------------------------------- quality */

export const QUALITY_METRICS: QualityMetric[] = [
  { id: 'q1', label: 'Опублікованих питань', value: '4 100', delta: '+96 за тиждень', tone: 'neutral', hint: 'Усі мають ревізію і статус.' },
  { id: 'q2', label: 'Середня правильність', value: '76%', delta: '−2 п.п.', tone: 'warn', hint: 'Норма 70–85%. Нижче 60% — питання надто складне або неоднозначне.' },
  { id: 'q3', label: 'Без посилання на Писання', value: '38', delta: '−14', tone: 'warn', hint: 'Не блокує публікацію, але потрапляє в чергу доопрацювання.' },
  { id: 'q4', label: 'Підозра на дублікат', value: '12', delta: '+3', tone: 'bad', hint: 'Схожість ≥ 0.86 у межах однієї теми.' },
  { id: 'q5', label: 'Зміщення до варіанта A', value: '31%', delta: '+6 п.п.', tone: 'bad', hint: 'Очікувано 25%. Вище — гравці вгадують за позицією.' },
  { id: 'q6', label: 'Скарги гравців', value: '7', delta: '−2', tone: 'good', hint: 'За останні 30 днів, усі розглянуті.' },
];

export const QUALITY_OUTLIERS = [
  { id: 'o-1', question: 'Скільки років Ной будував ковчег?', topic: 'Історія · Початки', accuracy: 0.18, plays: 1240, issue: 'Занадто складне: 18% правильних' },
  { id: 'o-2', question: 'Хто написав Євангеліє від Луки?', topic: 'Євангелія · Лука', accuracy: 0.97, plays: 3180, issue: 'Занадто легке: 97% правильних' },
  { id: 'o-3', question: 'Що сталося на горі Кармил?', topic: 'Пророки · Ілля', accuracy: 0.42, plays: 860, issue: 'Неоднозначне формулювання — 3 скарги' },
  { id: 'o-4', question: 'Яке місто збудував Каїн?', topic: 'Історія · Початки', accuracy: 0.51, plays: 640, issue: 'Дублікат q-2210 (схожість 0.91)' },
];

/* -------------------------------------------------------------- job tasks */

export const JOB_TASKS = [
  { id: 'questions:generate', label: 'Генерація питань', hint: 'Нові чернетки питань для теми' },
  { id: 'questions:repair', label: 'Ремонт питань', hint: 'Виправлення позначених валідацією' },
  { id: 'questions:dedupe', label: 'Пошук дублікатів', hint: 'Порівняння за embeddings у межах теми' },
  { id: 'explanations:repair', label: 'Ремонт пояснень', hint: 'Скорочення й вирівнювання тону' },
  { id: 'topics:expand', label: 'Конвеєр тем', hint: 'Пропозиції підтем із посиланнями' },
  { id: 'scripture:verify', label: 'Перевірка Писання', hint: 'Детермінований адаптер, без AI' },
] as const;
